# Generated by Django 3.2.8 on 2021-10-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='子菜单名')),
                ('href', models.CharField(max_length=128, verbose_name='链接地址')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('display', models.BooleanField(db_index=True, default=True, verbose_name='显示')),
                ('sort', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '子菜单',
                'verbose_name_plural': '子菜单管理',
            },
        ),
    ]
